[package]
name = "rubiks-simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
rand = "0.9.2"
getrandom = { version = "0.3.3", features = ["wasm_js"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1